### ISSUE TITLE
Using on nodejs

### ISSUE THREAD

**Issue by berrutti** [gabrielarchanjo/marvinj#9]
Hi! Is it possible to use this tool in a nodejs environment? I want to batch process images with the text recognition functions but I wasn't able to make it work. Thanks a lot

**Comment by berrutti** [comment]
I figured I can use OpenCV. Thanks for reading

**Comment by jusopi** [comment]
I too would like to use this in Node and cannot utilize OpenCV at this time.  Is there anyway to create this in a JS module?
